### ISSUE TITLE
realTime not working catching events yet

### ISSUE THREAD

**Issue by medisoft** [mean-expert-official/loopback-component-realtime#38]
Type: BUG
Version: Latest GIT	1.0.0-rc.8.5
Hello! I'm having this same problem as https://github.com/mean-expert-official/fireloop.io/issues/68

I see in the console as if the events were launched for upsert and create, but nothing arrives to the browser. 

When I do a remove then I receive the change event, also when I first subscribe I receive the change event.

```
  constructor(private rt: RealTime) {
    this.rt.onReady().subscribe((status: string) => {
      console.log('rt ' + status);
      this.transactionRef = this.rt.FireLoop.ref<Transaction>(Transaction);
      this.transactions = this.transactionRef.on('change');
      this.transactions.subscribe((txs) => {
        console.log('Change TXS', txs)
      });
    })
  }
```

```
@mean-expert/loopback-component-realtime: FireLoop starting create: Transaction: {"data":{},"parent":null}
@mean-expert/loopback-component-realtime: FireLoop value broadcasting
@mean-expert/loopback-component-realtime: FireLoop child_added broadcasting
@mean-expert/loopback-component-realtime: FireLoop change broadcasting
@mean-expert/loopback-component-realtime: FireLoop stats broadcasting


```
https://www.dropbox.com/s/z03fr8fdia5wnn0/Screenshot%202017-05-28%2003.13.14.png?dl=0
https://www.dropbox.com/s/aiqkee4b6cnhmcc/Screenshot%202017-05-28%2003.12.24.png?dl=0

**Comment by jonathan-casarrubias** [comment]
Hi @medisoft, it sounds to me that you are not configuring your Transaction model to use the FireLoop mixin as stated in the README https://github.com/mean-expert-official/loopback-component-realtime#enable-model-to-use-fireloop-api

````json
{
  "mixins": {
    "FireLoop": true
  }
}
````
I hope this helps you fix your problem

**Comment by davexs2020** [comment]
@jonathan-casarrubias, i'm not sure where to place this, is it in server/model-config.json? thanks

**Comment by jonathan-casarrubias** [comment]
@davexs2020 A mixing should be registered within any model you want to implement that functionality. In your case is common/models/transaction.json file, something like:

````json
{
  "name": "Transaction",
  "plural": "transactions",
  "properties": {},
   "mixins": {
    "FireLoop": true
  }
}
````

I hipe this helps you progress on this..

Cheers
Jon

**Comment by zuhrulumam** [comment]
it's working with 
`{
  "mixins": {
    "FireLoop": true
  }
}`
i think you should have generate that piece of code in fireloop generated code or in your tutorial (http://mean.expert/2016/11/10/angular-2-real-time-statistic-charts/), i mean, i almost give up from trying fireloop, becuse that official tutorial not working for me. 

thanks.

**Comment by jonathan-casarrubias** [comment]
@zuhrulumam I apologize you had a hard time with this configuration, it's a recent implementation and missed to update all the docs and generators.

I'm just publishing an update to generate the model config including by default the FireLoop: true flag.

Regards
Jon

**Comment by appunnicer13** [comment]
I am sorry to reopen this. But this was a general problem for me too. Wasted several hours on this. I too put the mixins in model-config.json. Please be more specific on your documentations, beginners get stuck a lot because of it. Thanks a lot.

**Comment by jonathan-casarrubias** [comment]
@appunnicer13 this has been specified in the readme almost a month ago

https://github.com/mean-expert-official/loopback-component-realtime#enable-model-to-use-fireloop-api

But also the fireloop cli already generates with the flag enabled

https://github.com/mean-expert-official/fireloop.io/blob/master/generator-fireloop/generators/model/index.js#L50

I'm sorry @appunnicer13 but you are in a totally different position than @zuhrulumam he didn't have a reference for this nor the cli was generating the configuration. In your case you could use the cli or simply fully read the readme for that information

**Comment by appunnicer13** [comment]
{
  "mixins": {
    "FireLoop": true
  }
}

 I am sorry, I read but I could only see this. May be it's not clear
because I am new to this. It wasn't exactly specifying which file I should
add this. Totally noob, sorry if I am saying anything wrong.

On 21 Jul 2017 7:38 p.m., "Jonathan Casarrubias" <notifications@github.com>
wrote:

@appunnicer13 <https://github.com/appunnicer13> this has been specified in
the readme almost a month ago

https://github.com/mean-expert-official/loopback-component-realtime#enable-
model-to-use-fireloop-api

But also the fireloop cli already generates with the flag enabled

https://github.com/mean-expert-official/fireloop.io/blob/master/generator-
fireloop/generators/model/index.js#L50

I'm sorry @appunnicer13 <https://github.com/appunnicer13> but you are in a
totally different position than @zuhrulumam <https://github.com/zuhrulumam>
he didn't have a reference for this nor the cli was generating the
configuration. In your case you could use the cli or simply fully read the
readme for that information

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mean-expert-official/loopback-component-realtime/issues/38#issuecomment-317010981>,
or mute the thread

**Comment by jonathan-casarrubias** [comment]
@appunnicer13 based on your last comment, I think I can improve the readme with a link for people to understand what exactly a mixin is.

It does state at the beginning of the paragraph

> From version 1.0.0-rc.8 you need to specify in which models you want to enable FireLoop events to be sent.

In there I state that in whatever model you want to enable the real time, you need to enable fireloop by setting up the mixin.

So I believe the missing part is to explain what exactly is a mixin, in that way you would be able to figure out that a mixin is installed within the model.json files, for those models that you want to enable the mixin.

Based on this issue I will improve the documentation in order to stop assuming that people will know what a mixin is and be more specific in those therms.

Thanks for giving back your feeback.

Regards!
Jon

**Comment by appunnicer13** [comment]
Thanks for supporting I have created a demo app myself please check it out
if you have time, Separated both front end and backend
https://github.com/appunnicer13/sample-notemaker
https://github.com/appunnicer13/sample-notemaker-frontend

here is a demo link http://sampleapp1.appunni.xyz/

Regards
Appunni M

<https://www.linkedin.com/in/appunni-m-b40056a0/>
<https://github.com/appunnicer13>

**Comment by Code-Crash** [comment]
@jonathan-casarrubias Hi, I'm getting the same error. any update on this issue?
I appreciate if there is an alternative way.

Thanks

**Comment by Code-Crash** [comment]
@jonathan-casarrubias Sorry man. 
My bad, It's working now. :)
